### ISSUE TITLE
The stable version of the documentation for the release 0.1.0 does not exist

### ISSUE THREAD

**Issue by ansjhenry** [ansys/scade-git#29]
### Description of the modifications

Create this version of the documentation.

**Comment by Revathyvenugopal162** [comment]
we need to the GitHub Actions release workflow for the repository at https://github.com/ansys/scade-git/actions/runs/10813554626/job/29998077091 and ensure that the stable documentation deploys successfully.

**Comment by ansjhenry** [comment]
Closed with PR #27.
